CREATE VIEW [V_LAST] AS 
select RECORD_TYPE, RECORD_DATE, AMOUNT from V_LAST_MILK
union
select RECORD_TYPE, RECORD_DATE, AMOUNT from V_LAST_JUICE
union
select RECORD_TYPE, RECORD_DATE, AMOUNT from V_LAST_SHIT;

